packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  ffmpeg-static: true
  sharp: true
minimumReleaseAgeExclude:
  - '@remotion/bundler@4.0.490'
  - '@remotion/canvas-capture@4.0.490'
  - '@remotion/captions@4.0.490'
  - '@remotion/compositor-darwin-arm64@4.0.490'
  - '@remotion/compositor-darwin-x64@4.0.490'
  - '@remotion/compositor-linux-arm64-gnu@4.0.490'
  - '@remotion/compositor-linux-arm64-musl@4.0.490'
  - '@remotion/compositor-linux-x64-gnu@4.0.490'
  - '@remotion/compositor-linux-x64-musl@4.0.490'
  - '@remotion/compositor-win32-x64-msvc@4.0.490'
  - '@remotion/eslint-config-flat@4.0.490'
  - '@remotion/licensing@4.0.490'
  - '@remotion/media-parser@4.0.490'
  - '@remotion/media-utils@4.0.490'
  - '@remotion/media@4.0.490'
  - '@remotion/player@4.0.490'
  - '@remotion/renderer@4.0.490'
  - '@remotion/streaming@4.0.490'
  - '@remotion/studio-shared@4.0.490'
  - '@remotion/studio@4.0.490'
  - '@remotion/timeline-utils@4.0.490'
  - '@remotion/web-renderer@4.0.490'
  - '@remotion/zod-types@4.0.490'
  - remotion@4.0.490
  - vite@8.1.5
