// Generated by scripts/generate-candidate-rig-review-implementation-receipt.ts.
// This is a verify-time implementation receipt, not a rendered-media receipt.
export const candidateRigReviewImplementationReceipt = {
  "schemaVersion": "1.0",
  "receiptKind": "candidate-rig-review-implementation-verification",
  "authorityDomain": "source-review-only",
  "implementationId": "generic-recipe-driven-2d-source-review",
  "implementationVersion": "2.0.0",
  "sourceNormalization": "utf8-nfc-lf-no-bom-v1",
  "evaluatorSourceContentHash": "b3e802aa20cdc04424f4107aad8509964a9395d8335592e1ea68e3deb27881ae",
  "exerciseSourceContentHash": "2a20b8b9bc59f3679c40fb2fce0932f8b6d7911a494eec66812905d097e76d40",
  "runtimeWrapperSourceContentHash": "188a0d65ca33615a1faad5a48809c307b2819c7f18dc177d7c9c1c0c2c111648",
  "publicBoundarySourceContentHash": "200d1f403bfe077657e7cd3a2b68064debf9ce8449f4a111930820505f33c1ad",
  "actorLocalKernelSourceContentHash": "9d59f3ae627ae6c11e8f4a0e0fe90032501ecd7df1fc98c900efbcc382704fa9",
  "receiptBuilderSourceContentHash": "cce9596314e37ed05fd0110fde88cfa018ec8810d9444d1c5fbc201738a2fee3",
  "generatorSourceContentHash": "f1b66742315dc28cdee40af1e9f8d61b009cbba2f0ee99935b354c79b9fa383a",
  "implementationSourceClosureContentHash": "cfbc71eff94e6d9183833ab95a32f1513fbc7bf14199c8b7ad4b078c474a7fe1",
  "canonicalFixtureContentHash": "059b9d5dad55a74b0fb7f2b8b65755561ac57edf360e76290c34ff026f04e529",
  "canonicalBehaviorContentHash": "68c46811800b945b95fa7198ecf7b12309ffd352234a87d449a5fa0f8601a88a",
  "exerciseDefinitionContentHash": "20956b3867b2fdcc068b32c073dc8efe440a5d53e05771ff4568ca1948fc9317",
  "evaluatedModes": [
    "clean",
    "overlay",
    "motion"
  ],
  "evaluatedViews": [
    "front",
    "profile-left",
    "profile-right"
  ],
  "evaluatedMotionFramesPerView": 180,
  "evaluatedMotionFrameCount": 540,
  "renderedMediaReceipt": false,
  "approvalAuthority": false,
  "capabilityAuthority": false,
  "productionBindable": false,
  "contentHash": "ff14b4868f2614d21de88379ec5dcd19161e3ac0ad61c25fcfde217e197288a3"
} as const;
