import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { hashCanonical } from "../packages/story-engine/src/canonical-hash";
import { buildCandidateRigReviewImplementationReceipt } from "../packages/story-engine/src/candidate-rig-review-implementation-receipt";
import { candidateRigReviewImplementationReceipt as trackedCandidateRigReviewImplementationReceipt } from "../packages/story-engine/src/candidate-rig-review-implementation-receipt.generated";

const assertKnownAnswerInvariants = (
  rawReceipt: Record<string, unknown>,
  label: string,
) => {
  const { contentHash, ...draft } = rawReceipt;
  const expectedSourceClosure = hashCanonical({
    evaluator: rawReceipt.evaluatorSourceContentHash,
    exercise: rawReceipt.exerciseSourceContentHash,
    runtimeWrapper: rawReceipt.runtimeWrapperSourceContentHash,
    publicBoundary: rawReceipt.publicBoundarySourceContentHash,
    actorLocalKernel: rawReceipt.actorLocalKernelSourceContentHash,
    receiptBuilder: rawReceipt.receiptBuilderSourceContentHash,
    generator: rawReceipt.generatorSourceContentHash,
  });
  const valid =
    contentHash === hashCanonical(draft) &&
    rawReceipt.implementationSourceClosureContentHash ===
      expectedSourceClosure &&
    JSON.stringify(rawReceipt.evaluatedModes) ===
      JSON.stringify(["clean", "overlay", "motion"]) &&
    JSON.stringify(rawReceipt.evaluatedViews) ===
      JSON.stringify(["front", "profile-left", "profile-right"]) &&
    rawReceipt.evaluatedMotionFramesPerView === 180 &&
    rawReceipt.evaluatedMotionFrameCount === 540 &&
    rawReceipt.renderedMediaReceipt === false &&
    rawReceipt.approvalAuthority === false &&
    rawReceipt.capabilityAuthority === false &&
    rawReceipt.productionBindable === false;
  if (!valid)
    throw new Error(
      `Candidate rig review ${label} fails fixed known-answer source-closure, transcript-coverage, content-hash, or authority invariants.`,
    );
};

const main = async () => {
  const root = resolve(process.cwd());
  const sourceFiles = {
    evaluatorSource: resolve(
      root,
      "packages/story-engine/src/candidate-rig-review-evaluator.ts",
    ),
    exerciseSource: resolve(
      root,
      "packages/story-engine/src/candidate-rig-review-exercise.ts",
    ),
    runtimeWrapperSource: resolve(
      root,
      "packages/story-engine/src/candidate-rig-review-runtime.ts",
    ),
    publicBoundarySource: resolve(
      root,
      "packages/story-engine/src/candidate-rig-review.ts",
    ),
    actorLocalKernelSource: resolve(
      root,
      "packages/story-engine/src/director/visual-performance-contract.ts",
    ),
    receiptBuilderSource: resolve(
      root,
      "packages/story-engine/src/candidate-rig-review-implementation-receipt.ts",
    ),
    generatorSource: resolve(
      root,
      "scripts/generate-candidate-rig-review-implementation-receipt.ts",
    ),
  };
  const generatedFile = resolve(
    root,
    "packages/story-engine/src/candidate-rig-review-implementation-receipt.generated.ts",
  );
  const receipt = buildCandidateRigReviewImplementationReceipt(
    Object.fromEntries(
      await Promise.all(
        Object.entries(sourceFiles).map(async ([key, file]) => [
          key,
          await readFile(file, "utf8"),
        ]),
      ),
    ) as Record<keyof typeof sourceFiles, string>,
  );
  const generated = `// Generated by scripts/generate-candidate-rig-review-implementation-receipt.ts.
// This is a verify-time implementation receipt, not a rendered-media receipt.
export const candidateRigReviewImplementationReceipt = ${JSON.stringify(receipt, null, 2)} as const;
`;

  if (process.argv.includes("--check")) {
    assertKnownAnswerInvariants(
      trackedCandidateRigReviewImplementationReceipt,
      "tracked generated literal",
    );
    assertKnownAnswerInvariants(receipt, "freshly evaluated receipt");
    const existing = await readFile(generatedFile, "utf8").catch(() => null);
    if (existing !== generated) {
      console.error(
        "Candidate rig review implementation receipt is stale. Run pnpm generate:candidate-rig-review-implementation-receipt and review the evaluator/behavior delta.",
      );
      process.exitCode = 1;
    }
    // This is a deterministic stale-receipt and known-answer review gate, not
    // cryptographic independence from a malicious generator rewrite. Any
    // coordinated source + generator + receipt regeneration remains governed
    // by normal code review of all bound source/hash deltas.
  } else {
    await writeFile(generatedFile, generated, "utf8");
    console.log(`Wrote ${generatedFile}`);
  }
};

void main();
